spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?connectTimeout=5000&socketTimeout=5000&createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
